<a href="https://colab.research.google.com/github/rishab-1903/ML_projects/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [155]:
  import pandas as pd
  car=pd.read_csv('/content/Quikr_car.csv')
  import matplotlib.pyplot as plt

In [156]:


 car.head()

,Unnamed: 0,Name,Label,Location,Price,Kms_driven,Fuel_type,Owner,Year,Company
0,0,Ford Figo Duratec Petrol EXI 1.2 - 2015,PLATINUM,Bangalore,"₹3,80,000","35,056 kms",Petrol,NaN,2015,Ford
1,1,Maruti Suzuki Wagon R VXI BS IV - 2016,PLATINUM,Bangalore,"₹4,65,000","44,000 kms",Petrol,NaN,2016,Maruti
2,2,Hyundai Creta 1.6 SX PLUS AUTO PETROL - 2018,PLATINUM,Bangalore,"₹13,50,000","42,917 kms",Petrol,NaN,2018,Hyundai
3,3,Hyundai Venue - 2019,PLATINUM,Chennai,"₹10,19,699","16,112 kms",Petrol,2nd Owner,2019,Hyundai
4,4,Honda Jazz - 2017,PLATINUM,Pune,"₹7,13,499","30,988 kms",Petrol,2nd Owner,2017,Honda

In [157]:
car.shape
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032 entries, 0 to 1031
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1032 non-null   int64
 1   Name        1032 non-null   object
 2   Label       1032 non-null   object
 3   Location    1030 non-null   object
 4   Price       1032 non-null   object
 5   Kms_driven  1032 non-null   object
 6   Fuel_type   1032 non-null   object
 7   Owner       740 non-null    object
 8   Year        1032 non-null   int64
 9   Company     1032 non-null   object
dtypes: int64(2), object(8)
memory usage: 80.8+ KB

In [158]:
car['Price'].unique()

array(['₹3,80,000', '₹4,65,000', '₹13,50,000', '₹10,19,699', '₹7,13,499',
       '₹3,91,099', '₹4,74,299', '₹12,52,999', '₹3,93,699', '₹7,30,899',
       '₹3,43,099', '₹7,07,599', '₹6,88,899', '₹14,21,599', '₹3,99,999',
       '₹14,73,299', '₹10,25,000', '₹7,35,000', '₹6,00,000', '₹8,00,000',
       '₹7,00,000', '₹8,20,000', '₹1,95,000', '₹18,50,000', '₹8,07,499',
       '₹5,22,999', '₹7,40,899', '₹11,41,999', '₹9,71,299', '₹6,40,999',
       '₹6,76,199', '₹5,62,399', '₹5,80,899', '₹7,70,999', '₹5,31,399',
       '₹3,67,299', '₹4,12,199', '₹14,60,099', '₹6,18,699', '₹4,85,000',
       '₹8,90,000', '₹2,45,000', '₹9,45,000', '₹5,90,000', '₹4,95,000',
       '₹4,75,000', '₹12,00,000', '₹4,90,199', '₹9,20,999', '₹5,54,399',
       '₹4,08,999', '₹12,48,299', '₹6,36,099', '₹4,52,699', '₹7,04,399',
       '₹5,53,599', '₹9,99,599', '₹6,84,699', '₹6,20,399', '₹5,49,899',
       '₹8,12,899', '₹6,56,699', '₹7,25,000', '₹37,00,000', '₹3,65,000',
       '₹2,80,000', '₹8,40,000', '₹8,18,599', '₹8,62,399', '₹6,73,599',
       '₹5,28,899', '₹5,27,999', '₹7,91,699', '₹3,92,999', '₹6,90,199',
       '₹4,74,699', '₹20,19,899', '₹5,62,299', '₹14,00,999', '₹4,47,599',
       '₹18,14,599', '₹9,20,399', '₹3,90,000', '₹6,50,000', '₹5,75,000',
       '₹5,25,000', '₹10,00,000', '₹3,25,000', '₹30,00,000', '₹3,43,299',
       '₹17,11,499', '₹9,18,799', '₹5,26,399', '₹8,81,099', '₹17,64,199',
       '₹6,39,199', '₹19,17,599', '₹4,66,599', '₹13,97,699', '₹5,04,399',
       '₹19,20,399', '₹9,17,599', '₹3,19,099', '₹4,84,399', '₹2,90,000',
       '₹17,90,000', '₹73,000', '₹22,00,000', '₹15,50,000', '₹4,20,000',
       '₹15,95,000', '₹5,73,499', '₹8,79,199', '₹7,33,399', '₹9,67,599',
       '₹15,39,299', '₹5,61,499', '₹10,42,699', '₹10,32,099', '₹9,03,499',
       '₹4,72,499', '₹7,71,299', '₹4,47,099', '₹5,04,599', '₹6,20,999',
       '₹4,33,999', '₹6,27,499', '₹3,60,000', '₹13,75,000', '₹69,000',
       '₹89,000', '₹44,25,000', '₹44,50,000', '₹7,04,199', '₹5,13,099',
       '₹4,69,399', '₹8,44,199', '₹5,44,799', '₹7,10,899', '₹5,80,599',
       '₹6,38,499', '₹6,54,699', '₹8,94,199', '₹8,58,599', '₹9,92,199',
       '₹7,14,999', '₹7,65,599', '₹18,00,299', '₹11,90,000', '₹14,52,000',
       '₹10,26,000', '₹8,21,000', '₹3,36,000', '₹2,00,000', '₹6,80,699',
       '₹7,14,899', '₹3,16,799', '₹6,75,099', '₹10,57,399', '₹9,38,099',
       '₹10,57,699', '₹6,10,099', '₹4,52,199', '₹7,12,699', '₹8,38,699',
       '₹6,66,899', '₹16,81,899', '₹18,54,599', '₹5,71,499', '₹5,89,199',
       '₹23,50,000', '₹36,50,000', '₹4,45,000', '₹12,31,000', '₹3,20,000',
       '₹11,75,000', '₹3,51,699', '₹2,99,199', '₹6,57,199', '₹5,39,299',
       '₹6,08,399', '₹10,42,799', '₹6,45,199', '₹8,11,899', '₹5,57,799',
       '₹8,73,999', '₹2,78,299', '₹9,86,399', '₹17,49,899', '₹4,43,899',
       '₹9,36,299', '₹8,50,000', '₹5,95,000', '₹1,75,000', '₹9,30,000',
       '₹15,00,000', '₹1,59,000', '₹4,04,499', '₹4,46,499', '₹10,47,499',
       '₹3,45,599', '₹7,84,399', '₹4,89,399', '₹2,88,399', '₹5,73,999',
       '₹13,73,699', '₹2,79,799', '₹6,58,199', '₹4,65,499', '₹5,63,999',
       '₹59,000', '₹1,19,000', '₹1,29,000', '₹29,31,000', '₹7,90,000',
       '₹7,18,699', '₹5,43,399', '₹17,80,399', '₹7,57,999', '₹10,13,999',
       '₹4,39,999', '₹8,39,199', '₹4,21,799', '₹9,86,799', '₹20,57,399',
       '₹10,82,299', '₹5,76,999', '₹5,33,199', '₹4,73,299', '₹18,38,399',
       '₹1,99,000', '₹17,50,000', 'Ask For Price', '₹18,90,000',
       '₹21,50,000', '₹6,99,000', '₹4,51,799', '₹4,46,999', '₹4,70,799',
       '₹5,11,799', '₹3,99,899', '₹3,75,999', '₹6,64,799', '₹6,17,799',
       '₹7,49,299', '₹7,95,799', '₹5,43,499', '₹3,17,199', '₹3,73,699',
       '₹5,01,799', '₹18,04,399', '₹1,70,000', '₹65,000', '₹2,99,000',
       '₹1,76,000', '₹9,85,299', '₹6,42,899', '₹7,40,000', '₹6,10,000',
       '₹5,10,000', '₹5,60,000', '₹4,55,000', '₹3,50,000', '₹4,63,099',
       '₹3,50,599', '₹6,36,299', '₹6,98,199', '₹7,64,199', '₹5,24,799',
       '₹18,31,000', '₹2,10,000', '₹22,50,000', '₹10,90,000', '₹3,75,000',
       '₹2,25,000', '₹4,93,899', '₹8,25,299', '₹4,95,499', '₹2,77,599',
       '₹4,73,899', '₹8,55,299', '₹5,40,299', '₹4,42,299', '₹7,25,399',
       '₹5,58,299', '₹3,54,299', '₹5,25,099', '₹6,75,000', '₹6,45,000',
       '₹7,85,000', '₹6,90,000', '₹4,25,000', '₹5,29,699', '₹10,81,899',
       '₹2,56,000', '₹12,44,799', '₹4,74,399', '₹3,89,399', '₹4,46,699',
       '₹9,18,999', '₹8,15,799', '₹8,96,799', '₹4,11,399', '₹4,98,999',
       '₹4,70,000', '₹9,25,000', '₹3,00,000', '₹4,50,000', '₹3,57,999',
       '₹4,62,599', '₹6,95,199', '₹4,90,399', '₹3,40,099', '₹9,97,899',
       '₹3,51,599', '₹6,03,799', '₹5,99,799', '₹4,56,099', '₹9,93,699',
       '₹3,12,299', '₹12,21,799', '₹3,23,399', '₹5,10,799', '₹7,50,000',
       '₹1,55,000', '₹4,10,000', '₹2,75,000', '₹1,45,000', '₹1,65,000',
       '₹9,10,799', '₹7,22,899', '₹8,09,499', '₹2,97,399', '₹4,11,999',
       '₹6,23,399', '₹3,72,399', '₹5,18,099', '₹4,85,599', '₹6,36,899',
       '₹3,96,999', '₹9,80,399', '₹6,58,999', '₹3,04,099', '₹3,62,599',
       '₹3,44,199', '₹2,15,000', '₹5,50,000', '₹79,000', '₹67,000',
       '₹4,62,399', '₹3,19,999', '₹2,75,699', '₹5,01,599', '₹5,06,599',
       '₹11,98,599', '₹7,75,499', '₹3,38,999', '₹6,52,699', '₹5,35,899',
       '₹4,92,099', '₹8,85,999', '₹6,94,899', '₹4,50,599', '₹3,77,999',
       '₹4,91,499', '₹18,65,000', '₹2,35,000', '₹15,75,000', '₹6,95,000',
       '₹2,95,000', '₹11,71,199', '₹6,25,699', '₹4,53,199', '₹8,50,499',
       '₹5,48,699', '₹4,98,799', '₹13,77,199', '₹7,72,799', '₹5,72,599',
       '₹7,74,899', '₹8,85,099', '₹6,87,499', '₹5,67,799', '₹3,98,499',
       '₹3,48,499', '₹5,20,899', '₹2,40,000', '₹5,00,000', '₹2,50,000',
       '₹9,75,000', '₹9,16,799', '₹4,80,999', '₹10,43,299', '₹7,87,399',
       '₹3,62,999', '₹4,03,199', '₹10,22,599', '₹4,83,199', '₹3,21,399',
       '₹3,07,999', '₹4,78,599', '₹4,05,199', '₹3,14,999', '₹6,84,599',
       '₹4,13,099', '₹3,45,000', '₹3,85,000', '₹8,25,000', '₹14,25,000',
       '₹5,01,199', '₹3,57,399', '₹4,94,199', '₹4,24,099', '₹5,98,299',
       '₹4,77,599', '₹7,03,999', '₹4,16,099', '₹5,59,099', '₹5,27,099',
       '₹15,17,999', '₹4,31,099', '₹5,39,799', '₹5,65,000', '₹4,35,000',
       '₹6,16,599', '₹16,56,999', '₹5,62,999', '₹4,88,899', '₹5,14,599',
       '₹4,95,299', '₹7,52,399', '₹4,74,799', '₹8,49,599', '₹6,63,199',
       '₹5,66,699', '₹4,71,199', '₹3,85,499', '₹4,91,599', '₹7,25,699',
       '₹4,60,000', '₹9,90,000', '₹1,90,000', '₹6,25,000', '₹6,40,099',
       '₹5,75,099', '₹7,26,399', '₹4,80,399', '₹3,69,599', '₹4,51,399',
       '₹4,94,099', '₹12,40,899', '₹2,86,199', '₹5,09,399', '₹3,78,099',
       '₹5,86,699', '₹9,06,899', '₹8,82,199', '₹5,07,999', '₹8,45,000',
       '₹13,25,000', '₹12,45,000', '₹7,82,999', '₹3,97,099', '₹3,92,099',
       '₹3,54,599', '₹7,19,599', '₹8,34,099', '₹3,65,899', '₹4,00,899',
       '₹3,20,199', '₹4,57,399', '₹7,17,699', '₹4,17,299', '₹3,23,199',
       '₹6,33,999', '₹7,95,000', '₹3,95,000', '₹3,30,000', '₹8,75,999',
       '₹3,09,399', '₹5,14,099', '₹6,72,899', '₹6,20,099', '₹7,33,999',
       '₹6,64,699', '₹4,54,299', '₹3,57,499', '₹4,22,299', '₹4,49,699',
       '₹4,93,499', '₹6,05,699', '₹7,55,099', '₹4,90,000', '₹1,60,000',
       '₹11,50,000', '₹3,49,000', '₹14,01,000', '₹4,32,699', '₹4,18,599',
       '₹2,75,799', '₹4,56,199', '₹7,28,499', '₹4,31,599', '₹5,33,099',
       '₹8,40,699', '₹4,86,499', '₹4,50,199', '₹4,18,999', '₹6,21,299',
       '₹5,08,399', '₹3,90,999', '₹36,00,000', '₹15,01,000', '₹11,00,000',
       '₹1,30,000', '₹4,64,199', '₹3,43,999', '₹4,41,499', '₹6,84,999',
       '₹8,15,399', '₹4,68,999', '₹11,94,799', '₹5,99,899', '₹7,10,199',
       '₹7,01,399', '₹8,34,599', '₹3,33,699', '₹3,49,799', '₹3,86,699',
       '₹10,50,000', '₹13,00,000', '₹6,59,199', '₹5,57,199', '₹4,26,199',
       '₹4,32,999', '₹4,58,399', '₹14,65,199', '₹7,83,099', '₹5,29,199',
       '₹4,47,199', '₹9,44,099', '₹4,52,099', '₹1,79,000', '₹7,75,000',
       '₹3,50,888', '₹2,23,299', '₹6,00,399', '₹3,67,399', '₹7,04,099',
       '₹3,77,899', '₹4,58,699', '₹5,66,199', '₹5,94,599', '₹6,78,699',
       '₹8,83,099', '₹5,78,099', '₹3,05,899', '₹9,90,888', '₹4,80,000',
       '₹8,41,499', '₹10,16,899', '₹7,48,599', '₹6,22,099', '₹5,30,699',
       '₹4,71,899', '₹5,05,399', '₹4,60,299', '₹6,83,999', '₹6,39,699',
       '₹5,10,499', '₹11,85,499', '₹5,79,899', '₹3,75,888', '₹7,78,888',
       '₹75,00,000', '₹5,82,899', '₹4,14,099', '₹5,16,599', '₹3,66,299',
       '₹3,75,899', '₹3,11,399', '₹5,01,999', '₹4,09,399', '₹17,37,899',
       '₹5,83,999', '₹6,54,299', '₹9,86,699', '₹4,14,199', '₹5,88,099',
       '₹8,75,000', '₹5,67,399', '₹8,05,099', '₹4,92,199', '₹4,95,799',
       '₹11,13,599', '₹2,99,999', '₹5,92,099', '₹3,22,299', '₹4,81,999',
       '₹5,34,599', '₹4,29,599', '₹7,23,799', '₹5,63,299', '₹2,14,199',
       '₹3,19,399', '₹1,80,000', '₹4,15,000', '₹4,30,000', '₹8,80,000',
       '₹8,10,399', '₹7,88,999', '₹5,08,799', '₹4,57,099', '₹6,12,899',
       '₹6,84,099', '₹7,16,699', '₹5,09,699', '₹3,37,799', '₹8,52,399',
       '₹17,84,699', '₹7,78,199', '₹7,05,099', '₹5,57,599', '₹15,18,099',
       '₹19,80,000', '₹10,59,000', '₹1,85,000', '₹7,10,000', '₹19,48,888',
       '₹22,72,499', '₹6,26,199', '₹2,36,099', '₹4,30,499', '₹4,42,799',
       '₹5,89,299', '₹2,98,199', '₹15,08,799', '₹4,73,699', '₹6,56,299',
       '₹3,45,799', '₹5,84,599', '₹7,86,799', '₹6,24,799', '₹4,72,399',
       '₹4,08,888', '₹2,88,888', '₹1,98,888', '₹8,98,888', '₹11,48,888',
       '₹97,000', '₹1,35,000', '₹6,87,199', '₹3,87,099', '₹6,50,599',
       '₹17,05,799', '₹5,26,899', '₹6,12,799', '₹2,69,099', '₹19,52,199',
       '₹6,46,299', '₹4,25,899', '₹4,96,399', '₹3,93,799', '₹6,19,599',
       '₹4,23,599', '₹8,31,999', '₹6,95,099', '₹9,80,000', '₹2,61,499',
       '₹6,49,699', '₹3,13,399', '₹21,22,099', '₹5,52,799', '₹4,90,099',
       '₹6,38,599', '₹3,74,799', '₹5,17,499', '₹5,53,899', '₹5,79,199',
       '₹5,31,999', '₹4,96,199', '₹6,59,099', '₹5,34,799', '₹9,50,000',
       '₹2,65,000', '₹74,999', '₹2,98,599', '₹4,22,999', '₹6,56,399',
       '₹6,88,599', '₹11,13,299', '₹5,87,399', '₹4,64,899', '₹3,02,699',
       '₹5,83,299', '₹8,77,999', '₹5,29,399', '₹4,39,000', '₹10,69,999',
       '₹5,89,999', '₹6,61,299', '₹4,29,099', '₹6,29,799', '₹3,97,299',
       '₹5,46,399', '₹4,12,999', '₹4,02,799', '₹9,15,699', '₹3,61,499',
       '₹3,57,899', '₹4,75,399', '₹4,85,299', '₹6,43,599', '₹2,55,000',
       '₹4,38,199', '₹9,24,599', '₹6,64,099', '₹4,62,299', '₹4,38,499',
       '₹6,80,999', '₹3,93,199', '₹6,46,799', '₹3,49,999', '₹4,19,599',
       '₹5,85,099', '₹6,27,799', '₹5,20,799', '₹4,10,199', '₹4,04,399',
       '₹6,82,799', '₹44,90,000', '₹1,50,000', '₹33,00,000', '₹20,00,000',
       '₹5,35,000', '₹10,45,799', '₹2,97,299', '₹9,80,199', '₹7,94,299',
       '₹4,11,899', '₹5,57,399', '₹8,96,099', '₹6,37,699', '₹2,54,499',
       '₹4,57,699', '₹3,61,599', '₹6,75,799', '₹3,89,499', '₹6,25,599',
       '₹6,86,999', '₹90,000', '₹6,20,000', '₹5,19,699', '₹3,24,599',
       '₹3,40,199', '₹6,93,999', '₹3,10,999', '₹7,22,199', '₹4,85,099',
       '₹6,14,999', '₹10,61,399', '₹8,79,699', '₹7,55,199', '₹8,16,399',
       '₹4,14,299', '₹4,76,299', '₹16,44,799', '₹4,40,000', '₹86,000',
       '₹3,52,199', '₹5,66,899', '₹6,50,699', '₹4,13,399', '₹6,45,799',
       '₹15,51,499', '₹8,11,799', '₹4,06,899', '₹7,27,299', '₹6,57,399',
       '₹6,37,599', '₹6,23,799', '₹4,22,899', '₹5,76,099', '₹19,87,699',
       '₹39,000', '₹3,26,000', '₹88,000', '₹16,52,199', '₹12,17,499',
       '₹11,98,299', '₹5,90,799', '₹8,44,999', '₹3,28,499', '₹7,69,599',
       '₹3,95,699', '₹2,94,799', '₹5,34,499', '₹6,81,399', '₹4,15,699',
       '₹3,00,199', '₹8,56,699', '₹4,81,399', '₹2,29,000'], dtype=object)

Owner nul values

In [159]:
backup=car.copy()

In [160]:
car=backup.copy()

In [161]:
 car['Price']=car['Price'].str.replace(',','')

In [162]:
car=car[car['Price']!='Ask For Price']

In [163]:
car['Price']=car['Price'].str.replace('₹','').astype(int)

In [164]:
car['Price']

0        380000
1        465000
2       1350000
3       1019699
4        713499
         ...
1027     229000
1028     275000
1029    1750000
1030    1750000
1031    1750000
Name: Price, Length: 1026, dtype: int64

In [165]:
car['Price'].unique()

array([ 380000,  465000, 1350000, 1019699,  713499,  391099,  474299,
       1252999,  393699,  730899,  343099,  707599,  688899, 1421599,
        399999, 1473299, 1025000,  735000,  600000,  800000,  700000,
        820000,  195000, 1850000,  807499,  522999,  740899, 1141999,
        971299,  640999,  676199,  562399,  580899,  770999,  531399,
        367299,  412199, 1460099,  618699,  485000,  890000,  245000,
        945000,  590000,  495000,  475000, 1200000,  490199,  920999,
        554399,  408999, 1248299,  636099,  452699,  704399,  553599,
        999599,  684699,  620399,  549899,  812899,  656699,  725000,
       3700000,  365000,  280000,  840000,  818599,  862399,  673599,
        528899,  527999,  791699,  392999,  690199,  474699, 2019899,
        562299, 1400999,  447599, 1814599,  920399,  390000,  650000,
        575000,  525000, 1000000,  325000, 3000000,  343299, 1711499,
        918799,  526399,  881099, 1764199,  639199, 1917599,  466599,
       1397699,  504399, 1920399,  917599,  319099,  484399,  290000,
       1790000,   73000, 2200000, 1550000,  420000, 1595000,  573499,
        879199,  733399,  967599, 1539299,  561499, 1042699, 1032099,
        903499,  472499,  771299,  447099,  504599,  620999,  433999,
        627499,  360000, 1375000,   69000,   89000, 4425000, 4450000,
        704199,  513099,  469399,  844199,  544799,  710899,  580599,
        638499,  654699,  894199,  858599,  992199,  714999,  765599,
       1800299, 1190000, 1452000, 1026000,  821000,  336000,  200000,
        680699,  714899,  316799,  675099, 1057399,  938099, 1057699,
        610099,  452199,  712699,  838699,  666899, 1681899, 1854599,
        571499,  589199, 2350000, 3650000,  445000, 1231000,  320000,
       1175000,  351699,  299199,  657199,  539299,  608399, 1042799,
        645199,  811899,  557799,  873999,  278299,  986399, 1749899,
        443899,  936299,  850000,  595000,  175000,  930000, 1500000,
        159000,  404499,  446499, 1047499,  345599,  784399,  489399,
        288399,  573999, 1373699,  279799,  658199,  465499,  563999,
         59000,  119000,  129000, 2931000,  790000,  718699,  543399,
       1780399,  757999, 1013999,  439999,  839199,  421799,  986799,
       2057399, 1082299,  576999,  533199,  473299, 1838399,  199000,
       1750000, 1890000, 2150000,  699000,  451799,  446999,  470799,
        511799,  399899,  375999,  664799,  617799,  749299,  795799,
        543499,  317199,  373699,  501799, 1804399,  170000,   65000,
        299000,  176000,  985299,  642899,  740000,  610000,  510000,
        560000,  455000,  350000,  463099,  350599,  636299,  698199,
        764199,  524799, 1831000,  210000, 2250000, 1090000,  375000,
        225000,  493899,  825299,  495499,  277599,  473899,  855299,
        540299,  442299,  725399,  558299,  354299,  525099,  675000,
        645000,  785000,  690000,  425000,  529699, 1081899,  256000,
       1244799,  474399,  389399,  446699,  918999,  815799,  896799,
        411399,  498999,  470000,  925000,  300000,  450000,  357999,
        462599,  695199,  490399,  340099,  997899,  351599,  603799,
        599799,  456099,  993699,  312299, 1221799,  323399,  510799,
        750000,  155000,  410000,  275000,  145000,  165000,  910799,
        722899,  809499,  297399,  411999,  623399,  372399,  518099,
        485599,  636899,  396999,  980399,  658999,  304099,  362599,
        344199,  215000,  550000,   79000,   67000,  462399,  319999,
        275699,  501599,  506599, 1198599,  775499,  338999,  652699,
        535899,  492099,  885999,  694899,  450599,  377999,  491499,
       1865000,  235000, 1575000,  695000,  295000, 1171199,  625699,
        453199,  850499,  548699,  498799, 1377199,  772799,  572599,
        774899,  885099,  687499,  567799,  398499,  348499,  520899,
        240000,  500000,  250000,  975000,  916799,  480999, 1043299,
        787399,  362999,  403199, 1022599,  483199,  321399,  307999,
        478599,  405199,  314999,  684599,  413099,  345000,  385000,
        825000, 1425000,  501199,  357399,  494199,  424099,  598299,
        477599,  703999,  416099,  559099,  527099, 1517999,  431099,
        539799,  565000,  435000,  616599, 1656999,  562999,  488899,
        514599,  495299,  752399,  474799,  849599,  663199,  566699,
        471199,  385499,  491599,  725699,  460000,  990000,  190000,
        625000,  640099,  575099,  726399,  480399,  369599,  451399,
        494099, 1240899,  286199,  509399,  378099,  586699,  906899,
        882199,  507999,  845000, 1325000, 1245000,  782999,  397099,
        392099,  354599,  719599,  834099,  365899,  400899,  320199,
        457399,  717699,  417299,  323199,  633999,  795000,  395000,
        330000,  875999,  309399,  514099,  672899,  620099,  733999,
        664699,  454299,  357499,  422299,  449699,  493499,  605699,
        755099,  490000,  160000, 1150000,  349000, 1401000,  432699,
        418599,  275799,  456199,  728499,  431599,  533099,  840699,
        486499,  450199,  418999,  621299,  508399,  390999, 3600000,
       1501000, 1100000,  130000,  464199,  343999,  441499,  684999,
        815399,  468999, 1194799,  599899,  710199,  701399,  834599,
        333699,  349799,  386699, 1050000, 1300000,  659199,  557199,
        426199,  432999,  458399, 1465199,  783099,  529199,  447199,
        944099,  452099,  179000,  775000,  350888,  223299,  600399,
        367399,  704099,  377899,  458699,  566199,  594599,  678699,
        883099,  578099,  305899,  990888,  480000,  841499, 1016899,
        748599,  622099,  530699,  471899,  505399,  460299,  683999,
        639699,  510499, 1185499,  579899,  375888,  778888, 7500000,
        582899,  414099,  516599,  366299,  375899,  311399,  501999,
        409399, 1737899,  583999,  654299,  986699,  414199,  588099,
        875000,  567399,  805099,  492199,  495799, 1113599,  299999,
        592099,  322299,  481999,  534599,  429599,  723799,  563299,
        214199,  319399,  180000,  415000,  430000,  880000,  810399,
        788999,  508799,  457099,  612899,  684099,  716699,  509699,
        337799,  852399, 1784699,  778199,  705099,  557599, 1518099,
       1980000, 1059000,  185000,  710000, 1948888, 2272499,  626199,
        236099,  430499,  442799,  589299,  298199, 1508799,  473699,
        656299,  345799,  584599,  786799,  624799,  472399,  408888,
        288888,  198888,  898888, 1148888,   97000,  135000,  687199,
        387099,  650599, 1705799,  526899,  612799,  269099, 1952199,
        646299,  425899,  496399,  393799,  619599,  423599,  831999,
        695099,  980000,  261499,  649699,  313399, 2122099,  552799,
        490099,  638599,  374799,  517499,  553899,  579199,  531999,
        496199,  659099,  534799,  950000,  265000,   74999,  298599,
        422999,  656399,  688599, 1113299,  587399,  464899,  302699,
        583299,  877999,  529399,  439000, 1069999,  589999,  661299,
        429099,  629799,  397299,  546399,  412999,  402799,  915699,
        361499,  357899,  475399,  485299,  643599,  255000,  438199,
        924599,  664099,  462299,  438499,  680999,  393199,  646799,
        349999,  419599,  585099,  627799,  520799,  410199,  404399,
        682799, 4490000,  150000, 3300000, 2000000,  535000, 1045799,
        297299,  980199,  794299,  411899,  557399,  896099,  637699,
        254499,  457699,  361599,  675799,  389499,  625599,  686999,
         90000,  620000,  519699,  324599,  340199,  693999,  310999,
        722199,  485099,  614999, 1061399,  879699,  755199,  816399,
        414299,  476299, 1644799,  440000,   86000,  352199,  566899,
        650699,  413399,  645799, 1551499,  811799,  406899,  727299,
        657399,  637599,  623799,  422899,  576099, 1987699,   39000,
        326000,   88000, 1652199, 1217499, 1198299,  590799,  844999,
        328499,  769599,  395699,  294799,  534499,  681399,  415699,
        300199,  856699,  481399,  229000])

In [166]:
car.info ()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1026 entries, 0 to 1031
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1026 non-null   int64
 1   Name        1026 non-null   object
 2   Label       1026 non-null   object
 3   Location    1024 non-null   object
 4   Price       1026 non-null   int64
 5   Kms_driven  1026 non-null   object
 6   Fuel_type   1026 non-null   object
 7   Owner       738 non-null    object
 8   Year        1026 non-null   int64
 9   Company     1026 non-null   object
dtypes: int64(3), object(7)
memory usage: 88.2+ KB

In [167]:
car['Kms_driven']=car['Kms_driven'].str.replace(',','')

In [168]:
car['Kms_driven']=car['Kms_driven'].str.replace(' kms','').astype(int)

In [169]:
car['Kms_driven'].unique()

array([ 35056,  44000,  42917,  16112,  30988,  69163,  42859,  34919,
        44940,  13687,  29848,  21426,  68177,  70650,  25730,  47096,
       131000,  26000,  58460,  48000,  26600,  36000,  39500,  76000,
        23698,  37860,  91830,  31172,   3243,   9616,  30249,  60875,
        25740,  38587,   3108,  35353,  34748,   2359,  17814,  68934,
        72600,  81000,  80000,  12000,   6000,  56000,  15840,  32482,
       113779,  26150,  34555,  30880,  70423,  30232,  50077,  18482,
        10246,  25021,  70646,  45490,  53306,  29000, 110000,  95000,
       170000,  58000,  22000,  69215,  33340,   9783,  15110,   3399,
        89310,  53148,  42020,  74594,   6110,  24346,  65668,  48644,
        36877,  79673,  54352,  64000,  54000,  40000, 107000,  38000,
        86000,  10000,  48658,  11998,  32513,  21372,  34178,  20547,
        34731,  30536,  10205,  25483,  39113,  43152,   5325,  44705,
        70022,  47435,  89000,   9826,  83000, 195000,  35000,  13000,
        46000,  72000,  29026,  59258, 120399,  28853,   9811,  43538,
        66400,  59341,  56246,  35944,  17699,  41065,   2311,   2991,
        29762,  91917,      0,  85000,  37000,  67000, 120000,  71000,
       105000,  30771,  29488,  36559,  38242,  66426,  16950,  18866,
        53245,  44543,  50128,  56349,  69524,  41218,   9085,  11292,
        75000,  28000,  51000,  24990,  48600,   3600, 115000,  29594,
        55953,  16980,  41828,  64803,  44460,  14276,  23425,  23056,
        16102,  56615,  70317,   6760,   8870,  78209,  64292,  57000,
        42000, 141000,  82000, 117000,  70000,  89450,  58771,  53266,
         9200,  61721,  18333,  51780,  30854,  24680,  85663,  20541,
        64182,  58819,  32057,  18403,   7877,  15509,  15000,  62000,
       134500,  63896,  90000,  48329,  21301,  34566,  34297, 119571,
        27957,  27210,  21610,  40902,  11057,  72505,  31338,  28674,
        25416,  14765,  60380,  73000,  55000,  79950,  19775,  28495,
        28344,  10801,   4365,  50866,  24230,  64275,   8924,  12208,
        26956,  12223,  23960,  33687,  24887,  74000,  45000,  41000,
        61000,  20000,  71423,  34095,  32658,  33166,  31284,  66090,
        51295,  48693,  36626,  55752,  49341,  60251,  22269,  38999,
        29110,  14506,  60000, 108252,  88000,  29115,  34763,  12500,
       124000,  78000,  44696,  33004,  46034,  60307,   8825,   5743,
        87000,  19500,  65000,  35623, 160000,  98500,  25735,  37522,
        38955,  65308,  30467,   1954,  35220,  75876,  27020,  13739,
        21544,  13816,  23817,  60985,  30123,  26123,  60123,  52123,
        11123,  41233,  50141,  86033,  30000,  86924,  68870,  22292,
        44013,  96250,  59839,  49693,  22223,   8030,  38780,  31919,
        47564,  42836,  27000, 690000, 135000,  50488,  12916,  30731,
        21627,   5580,  41371,  42313,  74913,  74760,  34045, 143147,
        28149,  38049,  78895,  27027,  66000,  47000,  82650,  23940,
        26678,  41342,  59614,  39550,  28621,  60437,  26598,  62723,
        21145,  48699,  10102,  34881,  53997,  49076,  65951, 116000,
       136000,  63000,  15032,  15575, 147819,  35203,   7597,  34883,
        59580,  49647,  67577,  10890,  57444,  33598,  17804,  62613,
        56974,   1405,   8000, 118000,  23000,  34000,  36965,  25526,
        20235,  61064,  12558,  14179,  20379,  42837,  67473,  27576,
        80900, 100934,  29060,  36129, 156442,  48710,  97000,  77000,
        20619,  51149,  12978,  40025,  63075,  78724,  12257,  26890,
        20485,  69220,  41900,  11944,  66143,  16563,  14460,  47120,
        79200,  48877,  32000,  14000,  79000, 147960,  38766,   8409,
        20718,  51125,  64459,  29467,  18019,  40710,   1956,  21531,
        20989,  33901,  54696,  50000,  53000,  52000, 149000,  27317,
        79784,  73656,  27664,  41898,   4889,  39836,  16108,  46111,
        23761, 146782,  26597,  12323,   3230,  62059,  28188,  49000,
        39226,  32877,  17283,  17419,  24416,  26700,  28979,  27150,
         3195,  26761,  71992,  27239,  36244,  69807,  31803,  92373,
       200000, 179000,  59000,  59612,  30212,  18113,  48435,  29297,
        53525,  15890,  31694,  36279,  33349, 103182,  63048,  26358,
        18932,  20369,  58769, 155000, 123920,  17900,  31041,  61875,
        29210,  35826,  29364,  16304,  95731,  31011,  30601,  14568,
        89559,  48834,  74190,  43077,  99000,  88500,  16000,  17981,
        20780,  56719,  31108,  33611,  43700,  49920,  57338,  23096,
        48732,  67924,  30418,  50593, 136381,  46943,  36277,   5600,
       150000,  70359,  42205,  60539,  16533,  26596,  30912,  17951,
        36928,  22854,  89156,  41999,  66145,  29157,  33882,  29379,
        17352,  16189,  41341,  19000,  91000,  13486,  33562,  13691,
        31980,  69526,  21492,  47425,  40988,  51983,  69376,  33094,
        26237,  42415, 112308,  61427,  59888,  58492,  75691,  84301,
        38346,  41530,  23049,  74510,  20141,  85860,  63133,  71894,
        95627,  75324,  64611,  77128,  36306,  83803, 108000,    700,
           25,    258,  81152,  75398,  42317,  60214,  58861,  27995,
        61018,  67109,  81811,  27357,  53293,  45260,   3139,  44690,
        13858,  25256,  94000,  44100, 126000,  15227,  87375,   7679,
        48378,  54645,   7211,  37217,  32372,  37947,  51886,  43187,
        33616,  91087,  26372,  58762, 101920,  63088,  54123,  35140,
        50842,  43412,  46201,  63626,  18251,  41019,  46463,  20110,
        17364,  35109,  44266,  39156,  57993,  51573,  39000,  87500,
        19900,  78329,  61977,  58640,  40650,  19121,  85893,   9874,
        25202,  95999,  49074,  52439,  10813, 127971, 114108,  52030,
        44721,  17000,  52500,  81500,  22667,  68519,  64011,  13598,
        47037,  69711,  49189,  18368,  16874,  24484,  20688,  24065,
        22609,  56523,  48031,  45578,  70070,  30030,  25000,  68000,
        28648,  59819,  19574,  46337,  73563,  51428,  95754,  34533,
        50154,  23492,  37739,  46178,  42893,  57875,   4832,  27805,
       140000,  68844,  37070,  20393,  22244,  47024,  64707,  52149,
        11203,  18071,  81412,  41912,  32516,  41552,  21790,  34010,
        50050,   2000, 125000,  75822,  28589,  15883,  63648, 156931,
        13829,  28361,  77960,  33473,  29052,  68041,  61361,  32218,
        28579,  51343,  86868,  35500,  19942,  17357,  14517,  13517,
        42302,  65783, 138716,  43339,  19526,  25673,  93304,  94409,
        66799,  27339,   9095,  21934,  51706,  31281,  46312,  32989,
        50599,  26127,  58118,  23534,  58978,  33103,  14600,  26049,
        33895,  32893,  61717,  82334,  87381, 210000,  24200,  34642,
       154104,  61826,  44751,   5183, 136082,   5817,  99138,  27936,
        39845,  15615,  53158,  16002,  31133,  20172,  69653, 132000,
        84000, 147000,  26023,  19805,  41365,  90001,  45285,  42441,
        24342,  14308,  32456,  58448,  86576,  50421,  26035,  23499,
        25636,  15023,    250,  22584,  22394,  93563,  10537,  81515,
        24676,  11917,  69654,  16226,   8925,  27819,  26543,  90088,
        34258, 101744,  19830,  13636,  21393,  76915,  16300,  40106,
        66461,  48182,  41816,  73841,  19908,  26226,  43287,  26527,
        37801,  54044,  29632,  31000])

In [170]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1026 entries, 0 to 1031
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1026 non-null   int64
 1   Name        1026 non-null   object
 2   Label       1026 non-null   object
 3   Location    1024 non-null   object
 4   Price       1026 non-null   int64
 5   Kms_driven  1026 non-null   int64
 6   Fuel_type   1026 non-null   object
 7   Owner       738 non-null    object
 8   Year        1026 non-null   int64
 9   Company     1026 non-null   object
dtypes: int64(4), object(6)
memory usage: 88.2+ KB

In [171]:
car['Name'].str.split(' ').str.slice(0,3).str.join(' ')

0          Ford Figo Duratec
1        Maruti Suzuki Wagon
2          Hyundai Creta 1.6
3            Hyundai Venue -
4               Honda Jazz -
                ...
1027       Hyundai i10 Magna
1028      Maruti Suzuki Alto
1029    Jeep Compass Limited
1030    Jeep Compass Limited
1031    Jeep Compass Limited
Name: Name, Length: 1026, dtype: object

In [172]:
car=car.drop(['Label'],axis=1)

In [173]:
car=car.drop(['Location'],axis=1)

In [174]:
car['Fuel_type']=car['Fuel_type'].str.replace(' ','')

In [175]:
car['Fuel_type'].unique()

array(['Petrol', 'Diesel', 'Electric', 'CNG', 'LPG', 'Petrol+CNG',
       'Hybrid'], dtype=object)

In [176]:
car['Owner'].unique()

array([nan, ' 2nd Owner', ' 1st Owner', ' 3rd Owner'], dtype=object)

In [177]:
car=car[car['Owner']!=car['Owner'].isna()]

In [178]:
car['Owner']=car['Owner'].str.replace(' 1st Owner','1')
car['Owner']=car['Owner'].str.replace(' 2nd Owner','2')
car['Owner']=car['Owner'].str.replace(' 3rd Owner','3')

In [179]:
car['Owner']=car.dropna(subset=['Owner'], inplace=True)

In [184]:
car=car.drop(['Owner'],axis=1)

In [185]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 738 entries, 3 to 1031
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  738 non-null    int64
 1   Name        738 non-null    object
 2   Price       738 non-null    int64
 3   Kms_driven  738 non-null    int64
 4   Fuel_type   738 non-null    object
 5   Year        738 non-null    int64
 6   Company     738 non-null    object
dtypes: int64(4), object(3)
memory usage: 46.1+ KB

In [186]:
car.head()

,Unnamed: 0,Name,Price,Kms_driven,Fuel_type,Year,Company
3,3,Hyundai Venue - 2019,1019699,16112,Petrol,2019,Hyundai
4,4,Honda Jazz - 2017,713499,30988,Petrol,2017,Honda
5,5,Hyundai i20 - 2013,391099,69163,Diesel,2013,Hyundai
6,6,Maruti Suzuki Swift Dzire VXi 1.2 BS IV - 2015,474299,42859,Petrol,2015,Maruti
7,7,Toyota Corolla Altis VL AT - 2017,1252999,34919,Petrol,2017,Toyota

In [187]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 738 entries, 3 to 1031
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  738 non-null    int64
 1   Name        738 non-null    object
 2   Price       738 non-null    int64
 3   Kms_driven  738 non-null    int64
 4   Fuel_type   738 non-null    object
 5   Year        738 non-null    int64
 6   Company     738 non-null    object
dtypes: int64(4), object(3)
memory usage: 46.1+ KB

In [188]:
car.describe()

        Unnamed: 0         Price     Kms_driven         Year
count   738.000000  7.380000e+02     738.000000   738.000000
mean    519.112466  6.803854e+05   42880.126016  2016.647696
std     301.479845  3.803416e+05   28497.835676     2.298132
min       3.000000  7.300000e+04     700.000000  2001.000000
25%     250.250000  4.471240e+05   22713.750000  2015.000000
50%     531.500000  5.730490e+05   36278.000000  2017.000000
75%     781.750000  7.819712e+05   58484.000000  2018.000000
max    1031.000000  3.300000e+06  210000.000000  2022.000000

In [189]:
car['Price'].unique()

array([1019699,  713499,  391099,  474299, 1252999,  730899,  343099,
        707599,  688899, 1421599,  399999, 1473299,  600000,  800000,
        807499,  522999,  740899, 1141999,  971299,  640999,  676199,
        562399,  580899,  770999,  531399,  367299,  412199, 1460099,
        618699,  485000,  245000, 1200000,  490199,  920999,  554399,
        408999, 1248299,  636099,  452699,  704399,  553599,  999599,
        684699,  620399,  549899,  812899,  656699,  725000,  818599,
        862399,  673599,  528899,  527999,  791699,  392999,  690199,
        474699, 2019899,  562299, 1400999,  447599, 1814599,  920399,
        525000,  343299, 1711499,  918799,  526399,  881099, 1764199,
        639199, 1917599,  466599, 1397699,  504399, 1920399,  917599,
        319099,  484399,   73000, 1550000,  420000, 1595000,  573499,
        879199,  733399,  967599, 1539299,  561499, 1042699, 1032099,
        903499,  472499,  771299,  447099,  504599,  620999,  433999,
        627499,  704199,  513099,  469399,  844199,  544799,  710899,
        580599,  638499,  654699,  894199,  858599,  992199,  714999,
        765599, 1800299, 1190000,  336000,  680699,  714899,  316799,
        675099, 1057399,  938099, 1057699,  610099,  452199,  712699,
        838699,  666899, 1681899, 1854599,  571499,  589199, 1231000,
        320000,  351699,  299199,  657199,  539299,  608399, 1042799,
        645199,  811899,  557799,  873999,  278299,  986399, 1749899,
        443899,  936299,  404499,  446499, 1047499,  345599,  784399,
        489399,  288399,  573999, 1373699,  279799,  658199,  465499,
        563999,  718699,  543399, 1780399,  757999, 1013999,  439999,
        839199,  421799,  986799, 2057399, 1082299,  576999,  533199,
        473299, 1838399, 1890000, 2150000,  699000,  451799,  446999,
        470799,  511799,  399899,  375999,  664799,  617799,  749299,
        795799,  543499,  317199,  373699,  501799, 1804399,  299000,
        176000,  325000,  985299,  642899,  740000,  463099,  350599,
        636299,  698199,  764199,  524799,  493899,  825299,  495499,
        277599,  473899,  855299,  540299,  442299,  725399,  558299,
        354299,  525099,  529699,  256000, 1244799,  474399,  389399,
        446699,  918999,  815799,  896799,  411399,  498999,  357999,
        462599,  695199,  490399,  340099,  997899,  351599,  603799,
        599799,  456099,  993699,  312299, 1221799,  323399,  510799,
        910799,  722899,  809499,  297399,  411999,  623399,  372399,
        518099,  485599,  636899,  396999,  980399,  658999,  304099,
        362599,  344199,  550000,  462399,  319999,  275699,  501599,
        506599, 1198599,  775499,  338999,  652699,  535899,  492099,
        885999,  694899,  450599,  377999,  491499, 1171199,  625699,
        453199,  850499,  548699,  498799, 1377199,  772799,  572599,
        774899,  885099,  687499,  567799,  398499,  348499,  520899,
        916799,  480999, 1043299,  787399,  362999,  403199, 1022599,
        483199,  321399,  307999,  478599,  405199,  314999,  684599,
        413099,  501199,  357399,  494199,  424099,  598299,  477599,
        703999,  416099,  559099,  527099, 1517999,  431099,  539799,
        616599, 1656999,  562999,  488899,  514599,  495299,  752399,
        474799,  849599,  663199,  566699,  471199,  385499,  491599,
        725699,  990000,  640099,  575099, 1081899,  726399,  480399,
        369599,  451399,  494099, 1240899,  286199,  509399,  378099,
        586699,  906899,  882199,  507999,  782999,  397099,  392099,
        354599,  719599,  834099,  365899,  400899,  320199,  457399,
        717699,  417299,  323199,  633999,  875999,  309399,  514099,
        672899,  620099,  733999,  664699,  454299,  357499,  422299,
        449699,  493499,  605699,  755099, 1401000,  432699,  418599,
        275799,  456199,  728499,  431599,  533099,  840699,  486499,
        450199,  418999,  621299,  508399,  390999, 1501000,  130000,
        464199,  343999,  441499,  684999,  815399,  468999, 1194799,
        599899,  710199,  701399,  834599,  333699,  349799,  386699,
       1300000,  659199,  557199,  426199,  432999,  458399, 1465199,
        783099,  529199,  447199,  944099,  452099,  795000,  350888,
        223299,  600399,  367399,  704099,  377899,  458699,  566199,
        594599,  678699,  883099,  578099,  305899, 1100000,  990888,
        841499, 1016899,  748599,  622099,  530699,  471899,  505399,
        460299,  683999,  639699,  510499, 1185499,  579899,  590000,
        375888,  778888, 1750000,  582899,  414099,  516599,  366299,
        375899,  311399,  501999,  409399, 1737899,  583999,  654299,
        986699,  414199,  588099,  567399,  805099,  492199,  495799,
       1113599,  299999,  592099,  322299,  481999,  534599,  429599,
        723799,  563299,  214199,  319399,  810399,  788999,  508799,
        457099,  612899,  684099,  716699,  509699,  337799,  852399,
       1784699,  778199,  705099,  557599, 1518099, 1059000,  185000,
       1948888, 2272499,  626199,  236099,  430499,  442799,  589299,
        298199, 1508799,  473699,  656299,  345799,  584599,  786799,
        624799,  472399,  408888,  288888,  198888,  898888, 1148888,
        687199,  387099,  650599, 1705799,  526899,  612799,  269099,
       1952199,  646299,  425899,  496399,  393799,  619599,  423599,
        831999,  695099,  390000,  261499,  649699,  313399, 2122099,
        552799,  490099,  638599,  374799,  517499,  553899,  579199,
        531999,  496199,  659099,  534799,  298599,  422999,  656399,
        688599, 1113299,  587399,  464899,  302699,  583299,  877999,
        529399,  950000,  439000, 1069999,  589999,  661299,  429099,
        629799,  397299,  546399,  412999,  402799,  915699,  357899,
        475399,  485299,  643599,  735000,  438199,  924599,  664099,
        462299,  438499,  680999,  393199,  646799,  349999,  419599,
        585099,  627799,  520799,  410199,  404399,  682799, 3300000,
       1175000, 1045799,  297299,  980199,  794299,  411899,  557399,
        896099,  637699,  254499,  457699,  361599,  675799,  389499,
        625599,  686999,  519699,  324599,  340199,  693999,  310999,
        722199,  485099,  614999, 1061399,  879699,  755199,  816399,
        414299,  476299, 1644799, 1500000, 1000000,  352199,  566899,
        650699,  413399,  645799, 1551499,  811799,  406899,  727299,
        657399,  637599,  623799,  422899,  576099, 1987699, 1652199,
       1217499, 1198299,  590799,  844999,  328499,  769599,  395699,
        294799,  534499,  681399,  415699,  300199,  856699,  481399,
        229000])

In [190]:
car['Price'].unique()

array([1019699,  713499,  391099,  474299, 1252999,  730899,  343099,
        707599,  688899, 1421599,  399999, 1473299,  600000,  800000,
        807499,  522999,  740899, 1141999,  971299,  640999,  676199,
        562399,  580899,  770999,  531399,  367299,  412199, 1460099,
        618699,  485000,  245000, 1200000,  490199,  920999,  554399,
        408999, 1248299,  636099,  452699,  704399,  553599,  999599,
        684699,  620399,  549899,  812899,  656699,  725000,  818599,
        862399,  673599,  528899,  527999,  791699,  392999,  690199,
        474699, 2019899,  562299, 1400999,  447599, 1814599,  920399,
        525000,  343299, 1711499,  918799,  526399,  881099, 1764199,
        639199, 1917599,  466599, 1397699,  504399, 1920399,  917599,
        319099,  484399,   73000, 1550000,  420000, 1595000,  573499,
        879199,  733399,  967599, 1539299,  561499, 1042699, 1032099,
        903499,  472499,  771299,  447099,  504599,  620999,  433999,
        627499,  704199,  513099,  469399,  844199,  544799,  710899,
        580599,  638499,  654699,  894199,  858599,  992199,  714999,
        765599, 1800299, 1190000,  336000,  680699,  714899,  316799,
        675099, 1057399,  938099, 1057699,  610099,  452199,  712699,
        838699,  666899, 1681899, 1854599,  571499,  589199, 1231000,
        320000,  351699,  299199,  657199,  539299,  608399, 1042799,
        645199,  811899,  557799,  873999,  278299,  986399, 1749899,
        443899,  936299,  404499,  446499, 1047499,  345599,  784399,
        489399,  288399,  573999, 1373699,  279799,  658199,  465499,
        563999,  718699,  543399, 1780399,  757999, 1013999,  439999,
        839199,  421799,  986799, 2057399, 1082299,  576999,  533199,
        473299, 1838399, 1890000, 2150000,  699000,  451799,  446999,
        470799,  511799,  399899,  375999,  664799,  617799,  749299,
        795799,  543499,  317199,  373699,  501799, 1804399,  299000,
        176000,  325000,  985299,  642899,  740000,  463099,  350599,
        636299,  698199,  764199,  524799,  493899,  825299,  495499,
        277599,  473899,  855299,  540299,  442299,  725399,  558299,
        354299,  525099,  529699,  256000, 1244799,  474399,  389399,
        446699,  918999,  815799,  896799,  411399,  498999,  357999,
        462599,  695199,  490399,  340099,  997899,  351599,  603799,
        599799,  456099,  993699,  312299, 1221799,  323399,  510799,
        910799,  722899,  809499,  297399,  411999,  623399,  372399,
        518099,  485599,  636899,  396999,  980399,  658999,  304099,
        362599,  344199,  550000,  462399,  319999,  275699,  501599,
        506599, 1198599,  775499,  338999,  652699,  535899,  492099,
        885999,  694899,  450599,  377999,  491499, 1171199,  625699,
        453199,  850499,  548699,  498799, 1377199,  772799,  572599,
        774899,  885099,  687499,  567799,  398499,  348499,  520899,
        916799,  480999, 1043299,  787399,  362999,  403199, 1022599,
        483199,  321399,  307999,  478599,  405199,  314999,  684599,
        413099,  501199,  357399,  494199,  424099,  598299,  477599,
        703999,  416099,  559099,  527099, 1517999,  431099,  539799,
        616599, 1656999,  562999,  488899,  514599,  495299,  752399,
        474799,  849599,  663199,  566699,  471199,  385499,  491599,
        725699,  990000,  640099,  575099, 1081899,  726399,  480399,
        369599,  451399,  494099, 1240899,  286199,  509399,  378099,
        586699,  906899,  882199,  507999,  782999,  397099,  392099,
        354599,  719599,  834099,  365899,  400899,  320199,  457399,
        717699,  417299,  323199,  633999,  875999,  309399,  514099,
        672899,  620099,  733999,  664699,  454299,  357499,  422299,
        449699,  493499,  605699,  755099, 1401000,  432699,  418599,
        275799,  456199,  728499,  431599,  533099,  840699,  486499,
        450199,  418999,  621299,  508399,  390999, 1501000,  130000,
        464199,  343999,  441499,  684999,  815399,  468999, 1194799,
        599899,  710199,  701399,  834599,  333699,  349799,  386699,
       1300000,  659199,  557199,  426199,  432999,  458399, 1465199,
        783099,  529199,  447199,  944099,  452099,  795000,  350888,
        223299,  600399,  367399,  704099,  377899,  458699,  566199,
        594599,  678699,  883099,  578099,  305899, 1100000,  990888,
        841499, 1016899,  748599,  622099,  530699,  471899,  505399,
        460299,  683999,  639699,  510499, 1185499,  579899,  590000,
        375888,  778888, 1750000,  582899,  414099,  516599,  366299,
        375899,  311399,  501999,  409399, 1737899,  583999,  654299,
        986699,  414199,  588099,  567399,  805099,  492199,  495799,
       1113599,  299999,  592099,  322299,  481999,  534599,  429599,
        723799,  563299,  214199,  319399,  810399,  788999,  508799,
        457099,  612899,  684099,  716699,  509699,  337799,  852399,
       1784699,  778199,  705099,  557599, 1518099, 1059000,  185000,
       1948888, 2272499,  626199,  236099,  430499,  442799,  589299,
        298199, 1508799,  473699,  656299,  345799,  584599,  786799,
        624799,  472399,  408888,  288888,  198888,  898888, 1148888,
        687199,  387099,  650599, 1705799,  526899,  612799,  269099,
       1952199,  646299,  425899,  496399,  393799,  619599,  423599,
        831999,  695099,  390000,  261499,  649699,  313399, 2122099,
        552799,  490099,  638599,  374799,  517499,  553899,  579199,
        531999,  496199,  659099,  534799,  298599,  422999,  656399,
        688599, 1113299,  587399,  464899,  302699,  583299,  877999,
        529399,  950000,  439000, 1069999,  589999,  661299,  429099,
        629799,  397299,  546399,  412999,  402799,  915699,  357899,
        475399,  485299,  643599,  735000,  438199,  924599,  664099,
        462299,  438499,  680999,  393199,  646799,  349999,  419599,
        585099,  627799,  520799,  410199,  404399,  682799, 3300000,
       1175000, 1045799,  297299,  980199,  794299,  411899,  557399,
        896099,  637699,  254499,  457699,  361599,  675799,  389499,
        625599,  686999,  519699,  324599,  340199,  693999,  310999,
        722199,  485099,  614999, 1061399,  879699,  755199,  816399,
        414299,  476299, 1644799, 1500000, 1000000,  352199,  566899,
        650699,  413399,  645799, 1551499,  811799,  406899,  727299,
        657399,  637599,  623799,  422899,  576099, 1987699, 1652199,
       1217499, 1198299,  590799,  844999,  328499,  769599,  395699,
        294799,  534499,  681399,  415699,  300199,  856699,  481399,
        229000])

In [192]:
car[car['Price']<6e6]

,Unnamed: 0,Name,Price,Kms_driven,Fuel_type,Year,Company
3,3,Hyundai Venue - 2019,1019699,16112,Petrol,2019,Hyundai
4,4,Honda Jazz - 2017,713499,30988,Petrol,2017,Honda
5,5,Hyundai i20 - 2013,391099,69163,Diesel,2013,Hyundai
6,6,Maruti Suzuki Swift Dzire VXi 1.2 BS IV - 2015,474299,42859,Petrol,2015,Maruti
7,7,Toyota Corolla Altis VL AT - 2017,1252999,34919,Petrol,2017,Toyota
...,...,...,...,...,...,...,...
1023,1023,Ford Figo Aspire - 2017,481399,29632,Petrol,2017,Ford
1027,1027,Hyundai i10 Magna 1.2 - 2014,229000,65000,Petrol,2014,Hyundai
1029,1029,Jeep Compass Limited 2.0 Diesel - 2017,1750000,31000,Diesel,2017,Jeep
1030,1030,Jeep Compass Limited 2.0 Diesel - 2017,1750000,31000,Diesel,2017,Jeep
1031,1031,Jeep Compass Limited 2.0 Diesel - 2017,1750000,31000,Diesel,2017,Jeep

In [193]:
car.reset_index()

,index,Unnamed: 0,Name,Price,Kms_driven,Fuel_type,Year,Company
0,3,3,Hyundai Venue - 2019,1019699,16112,Petrol,2019,Hyundai
1,4,4,Honda Jazz - 2017,713499,30988,Petrol,2017,Honda
2,5,5,Hyundai i20 - 2013,391099,69163,Diesel,2013,Hyundai
3,6,6,Maruti Suzuki Swift Dzire VXi 1.2 BS IV - 2015,474299,42859,Petrol,2015,Maruti
4,7,7,Toyota Corolla Altis VL AT - 2017,1252999,34919,Petrol,2017,Toyota
...,...,...,...,...,...,...,...,...
733,1023,1023,Ford Figo Aspire - 2017,481399,29632,Petrol,2017,Ford
734,1027,1027,Hyundai i10 Magna 1.2 - 2014,229000,65000,Petrol,2014,Hyundai
735,1029,1029,Jeep Compass Limited 2.0 Diesel - 2017,1750000,31000,Diesel,2017,Jeep
736,1030,1030,Jeep Compass Limited 2.0 Diesel - 2017,1750000,31000,Diesel,2017,Jeep
737,1031,1031,Jeep Compass Limited 2.0 Diesel - 2017,1750000,31000,Diesel,2017,Jeep

In [194]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 738 entries, 3 to 1031
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  738 non-null    int64
 1   Name        738 non-null    object
 2   Price       738 non-null    int64
 3   Kms_driven  738 non-null    int64
 4   Fuel_type   738 non-null    object
 5   Year        738 non-null    int64
 6   Company     738 non-null    object
dtypes: int64(4), object(3)
memory usage: 46.1+ KB

In [198]:
 car.to_csv('Cleaned car.csv')
 car=car.reset_index()

In [222]:
car['Company'].unique()

array(['Hyundai', 'Honda', 'Maruti', 'Toyota', 'Jeep', 'Kia', 'Ford',
       'Tata', 'Renault', 'Nissan', 'MG', 'Mahindra', 'Volkswagen',
       'Skoda', 'Mercedes', 'BMW', 'Jaguar', 'Fiat', 'Datsun', 'Audi',
       'Volvo', 'Chevrolet', 'Porsche'], dtype=object)

In [231]:
car=car.drop(columns='Unnamed: 0',axis=1)

In [233]:
car=car.drop(columns='index',axis=1)

In [234]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        738 non-null    object
 1   Price       738 non-null    int64
 2   Kms_driven  738 non-null    int64
 3   Fuel_type   738 non-null    object
 4   Year        738 non-null    int64
 5   Company     738 non-null    object
dtypes: int64(3), object(3)
memory usage: 34.7+ KB

Model

In [235]:
X=car.drop(columns='Price')
y=car['Price']

In [236]:
y

0      1019699
1       713499
2       391099
3       474299
4      1252999
        ...
733     481399
734     229000
735    1750000
736    1750000
737    1750000
Name: Price, Length: 738, dtype: int64

In [237]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [238]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [239]:
car['Year'].unique()

array([2019, 2017, 2013, 2015, 2018, 2016, 2020, 2021, 2014, 2012, 2011,
       2001, 2022, 2010, 2007])

In [240]:
 ohe=OneHotEncoder()
 ohe.fit(X[['Name','Company','Kms_driven','Fuel_type','Year']])

OneHotEncoder()

In [241]:
c_t= make_column_transformer((OneHotEncoder(categories=ohe.categories_),['Name','Company','Kms_driven','Fuel_type','Year']),remainder='passthrough')

In [242]:
lr=LinearRegression()

In [243]:
pipe=make_pipeline(c_t,lr)

In [244]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi Q3 - 2015', 'BMW 3 Series 320d - 2013',
       'BMW 3 Series 320d Luxury Line - 2015',
       'BMW 5 Series 523i Sedan - 2010', 'Chevrolet Sail 1.2 LS - 2013',
       'Datsun Redi GO - 2017', 'Datsun Redi GO - 2018',
       'Datsun Redi GO T O  - 2021', 'Fiat Linea Dynamic 1.3 - 201...
       117000, 119571, 120399, 123920, 127971, 136000, 136082, 136381,
       138716, 143147, 146782, 147819, 147960, 154104, 156442, 156931,
       195000, 210000]),
                                                                            array(['CNG', 'Diesel', 'Electric', 'Hybrid', 'Petrol', 'Petrol+CNG'],
      dtype=object),
                                                                            array([2001, 2007, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022])]),
                                                  ['Name', 'Company',
                                                   'Kms_driven', 'Fuel_type',
                                                   'Year'])])),
                ('linearregression', LinearRegression())])

In [245]:
y_pred = pipe.predict(X_test)

In [247]:
y_pred

array([1393301.33003401,  388749.98830593,  466028.20538559,
       1508306.01889084, 1759047.83912547, 1017434.35629653,
        742848.69330295,  681172.28002482,  617607.70276866,
        460383.61757485,  531681.03129206,  910483.47992884,
        542872.03786474,  742722.68907265,  857710.74651069,
        614202.5098424 ,  803706.52327699, 1229533.58452333,
        646346.86010821,  483256.19628503,  514599.91140494,
       1083229.80897014,  513632.84235817,  543701.70777356,
        385983.59340175, 1124181.30313411,  508793.83724272,
       1625817.30863306,  658740.51191402,  493281.03365773,
        652705.07152412,  508793.83724272,  561966.85780107,
        514599.91140494,  448958.8651403 ,  626173.13950796,
        586105.486009  ,  673921.9498859 ,  513632.84235817,
        948244.55303148,  505349.71757139,  482000.73998068,
        733792.31661407,  438997.69506601,  614202.5098424 ,
        672780.61062137,  507901.76754963,  751320.41380996,
        756794.70729734,  614202.5098424 ,  571750.34603944,
        354504.47145055, 1622154.57006368,  551738.89722113,
        626173.13950796,  663639.162255  ,  823754.75646248,
        399999.02305634,  614202.5098424 ,  368535.21925665,
       1750000.03544677,  631222.03963302,  651756.47773879,
        626173.13950796,  590000.34640471,  626173.13950796,
        818669.86211315, 1073787.48708215, 1917598.82221109,
        951148.69934925,  386907.23847698,  551105.61353655,
       1450478.76943751,  706279.33332964,  416257.23906441,
        429130.39482512,  561966.85780107,  385983.59340175,
        454032.85472212,  634878.63140934, 1401000.22551919,
        363774.00591631,  713005.48392403,  775609.49944359,
        356401.17099505,  430983.59269959,  620066.57157422,
        505349.71757139,  507901.76754963,  617607.70276866,
        763607.41950925,  633625.51638063,  571750.34603944,
        677713.83460698,  514599.91140494, 1508306.01889084,
        642033.2368876 ,  917324.06017905,  836187.69953063,
        626173.13950796, 1458797.01777373,  938211.39619471,
       1175557.60079149,  360721.95303287,  504598.99778491,
        382815.47431922,  426647.70442942,  532379.28479628,
        475615.90087675,  652705.07152412,  421167.46452139,
        846024.05875201,  483256.19628503,  508793.83724272,
        524798.98056121,  677713.83460698,  382815.47431922,
        836187.69953063,  614353.08132195,  686293.9052285 ,
       1804399.06378122, 1362465.73072881,  617607.70276866,
        360721.95303287,  525000.05283232,  514599.91140494,
        694089.84446708,  633625.51638063,  681172.28002482,
        598190.38773034,  626173.13950796,  505349.71757139,
        508793.83724272,  354504.47145055, 1212697.82337876,
        938211.39619471,  445966.15596969,  482000.73998068,
        831025.08772686,  456383.22175725, 1355886.91630745,
        591485.14675346,  471100.34402498,  614202.5098424 ,
        633625.51638063,  769540.85260605,  585959.78479436,
        450800.34361868])

In [248]:
r2_score(y_test,y_pred)

0.6407068693287722

In [264]:
a=['Ford Figo Aspire - 2017',16112,'Petrol',2019,	'Ford']

In [265]:
pipe.predict(pd.DataFrame([a],columns=['Name','Kms_driven','Fuel_type','Year','Company']))

array([769383.50432707])